---
- hosts: localhost 
  roles: 
    - create-gcp
  gather_facts: no
  connection: local
  vars:
    - gcp_project: "{{ lookup('ansible.builtin.env','GCP_PROJECT') }}"
    - gcp_cred_kind: "{{ lookup('ansible.builtin.env','GCP_CRED_KIND') }}"
    - gcp_cred_file: "{{ lookup('ansible.builtin.env','GCP_CRED_FILE') }}"
    - gcp_cred_email: "{{ lookup('ansible.builtin.env','GCP_CRED_EMAIL') }}"
    - zone: "{{ lookup('ansible.builtin.env','GCP_ZONE') }}"
    - region: "{{ lookup('ansible.builtin.env','GCP_REGION') }}"
  post_tasks:
    - name: Wait to SSH into instance
      wait_for: delay=5 sleep=5 host={{ address.address }} port=22 state=started timeout=100

- hosts: gcp_instance
  become: true
  become_user: root
  pre_tasks:
    - name: Probe python installation
      raw: command -v python3 || true
      changed_when: false
      register: python_available
    - name: Bootstrap a host without python installed
      raw: dnf install python3 python3-libselinux
      when: "'python' not in python_available.stdout"
    - name: Ensure Python 3 is available
      dnf:
        name: python3
        state: present
    - name: Install libselinux-python3
      dnf:
        name: libselinux-python3
        state: present
  roles:
    - keylime-gcp    
