---
galaxy_info:
  author: Avery Blanchard
  description: Keylime GCP
  company: Red Hat
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - 35
  galaxy_tags: []
dependencies: []
